---
abstract: 'Coptic Calendar System.'
author:
  - 'Daniel Yacob <dyacob@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-Calendar-Coptic
no_index:
  directory:
    - t
    - inc
requires:
  Class::Factory::Util: '0'
  Convert::Number::Coptic: '0'
  DateTime: '0'
  perl: '5.008000'
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
