---
abstract: 'Coptic Calendar System.'
author:
  - 'Daniel Yacob <dyacob\@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-Calendar-Coptic
provides:
  DateTime::Calendar::Coptic:
    file: lib/DateTime/Calendar/Coptic.pm
    version: '0.04'
  DateTime::Calendar::Coptic::Languages:
    file: lib/DateTime/Calendar/Coptic/Languages.pm
    version: '0.04'
  DateTime::Calendar::Coptic::Languages::Arabic:
    file: lib/DateTime/Calendar/Coptic/Languages/Arabic.pm
    version: '0.04'
  DateTime::Calendar::Coptic::Languages::Coptic:
    file: lib/DateTime/Calendar/Coptic/Languages/Coptic.pm
    version: '0.04'
  DateTime::Calendar::Coptic::Languages::English:
    file: lib/DateTime/Calendar/Coptic/Languages/English.pm
    version: '0.04'
  DateTime::Calendar::CopticEthiopic:
    file: lib/DateTime/Calendar/CopticEthiopic.pm
    version: '0.13'
  DateTime::Languages:
    file: lib/DateTime/Languages.pm
    version: '0.04'
requires:
  Class::Factory::Util: '0'
  Convert::Number::Coptic: '0'
  DateTime: '0'
  Params::Validate: '0'
  perl: v5.6.1
resources:
  bugtracker: https://github.com/dyacob/DateTime-Calendar-Coptic/issues
  homepage: https://github.com/dyacob/DateTime-Calendar-Coptic
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dyacob/DateTime-Calendar-Coptic.git
version: '0.04'
x_authority: cpan:dyacob
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
